name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-lastest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_sorteador_app npm run test
